version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: api-docker-container
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  
  web:
    build:
      context: ./web
    container_name: web-docker-container
    ports:
      - '3000:3000'